POST https://{{domain}}/rest/api/3/issue/{{task}}/worklog
Content-Type: application/json
Authorization: {{key}}

{
  "timeSpentSeconds": 60,
  "visibility": {},
  "comment": {
    "type": "doc",
    "version": 1,
    "content": [
      {
        "type": "paragraph",
        "content": [
          {
            "text": "time logged by jlog cli tool",
            "type": "text"
          }
        ]
      }
    ]
  },
  "started": "2021-03-21T18:49:08.564+0000"
}

###
GET https://{{domain}}/rest/api/3/issue/{{task}}/worklog
Content-Type: application/json
Authorization: {{key}}

{}

###
